# Generated by Django 5.2.14 on 2026-06-14 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_account', '0003_addpatient_origin_clinic_alter_addpatient_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField(default=0)),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('pre_pain', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pre_bp', models.CharField(blank=True, max_length=20, null=True)),
                ('pre_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pre_notes', models.TextField(blank=True, null=True)),
                ('post_pain', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('progress_status', models.CharField(blank=True, choices=[('much_worse', 'Much worse'), ('worse', 'Worse'), ('same', 'Same'), ('better', 'Better'), ('much_better', 'Much better')], max_length=20, null=True)),
                ('treatment_response', models.CharField(blank=True, max_length=20, null=True)),
                ('post_remarks', models.TextField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True, null=True)),
                ('next_session', models.DateField(blank=True, null=True)),
                ('session_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='personal_account.addpatient')),
            ],
            options={
                'ordering': ['-session_date'],
                'unique_together': {('patient', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='TreatmentSessionModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict)),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription_app.modality')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_modalities', to='prescription_app.treatmentsession')),
            ],
            options={
                'unique_together': {('session', 'modality')},
            },
        ),
    ]
