# Generated by Django 5.2.14 on 2026-06-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0003_addpatient_origin_clinic_alter_addpatient_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatient',
            name='completed_session',
            field=models.IntegerField(default=0),
        ),
    ]
