# Generated by Django 5.2.14 on 2026-06-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0004_addpatient_completed_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatient',
            name='qr_code',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addpatient',
            name='qr_token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
